global org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder scoreHolder;

// ############################################################################
// Hard constraints
// ############################################################################

rule "count asc"
    when
        $intValue:IntValuePlanningEntity($intValue == 0)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -1);
end